spring.application.name=AI-Powered Code Review and Bug Detection System

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/code_backend
spring.datasource.username=postgres
spring.datasource.password=Musharraf@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=442468838813-tk80cdo4etqef8t199uldqg2laqhco2h.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
app.frontend.url=http://localhost:5173